### ISSUE TITLE
Should expose on window instead of WebSQL

### ISSUE THREAD

**Issue by joeljeske** [Thinkwise/cordova-plugin-websql#10]
Currently, this plugin exposes itself as `window.WebSQL.openDatabase`. To be consistent as a websql plugin, it should also/instead expose as `window.openDatabase`. 

This could be fixed by changing [this line in config.xml](https://github.com/Thinkwise/cordova-plugin-websql/blob/6147a4bafd6cec2286e09e2663d89297e26fa9e8/plugin.xml#L15) to read

``` xml
<merges target="window" /> 
```

instead of 

``` xml
<clobbers target="window.WebSQL" />
```

This is also consistent with the forked project.

**Comment by JamesMessinger** [comment]
+1

Once this change is made, I'll update [this line](https://github.com/ABB-Austin/cordova-plugin-indexeddb-async/blob/master/www/requireWebSql.js#L3) in the [cordova-plugin-indexeddb-async](https://github.com/ABB-Austin/cordova-plugin-indexeddb-async) plug-in.

**Comment by masonicboom** [comment]
Agreed. @joeljeske: submit a PR?
