### ISSUE TITLE
Database erased when you kill the app

### ISSUE THREAD

**Issue by jantonsg** [Thinkwise/cordova-plugin-websql#13]
Hi, 

I am Developing a cross platform app. Where one of the platforms is Windows Phone 8.1. Previously with Windows Phone 8 I was using IndexedDB but in WP8.1 it has been deprecated and we need alternatives.

After a hard work finding and testing plugins I have found it. And I am very satisfied with it but...

I have a problem, my DATABASE IS ERASED when you kill the app. 

However if you close the app(it is maintained on background) or device is turned off and turned on again the database is OK. But If you open the app and kill it, database seems to be erased next time you try to open the app. 

I have changed plugin.xml <clobbers> tag as joeljeske commented on an issue reported here(https://github.com/Thinkwise/cordova-plugin-websql/issues/10). Without this change I am not able to make database works on my app.

Could you help me? If I could help or you need more information about the issue, count with me. 

Btw, I am trying to find where the database is stored on my windows phone, to try to debug it, but I am not able to find it. Could you give any clue to find it?

Thanks so much,

**Comment by DickvdBrink** [comment]
I was unable to reproduce this. Are you sure you are opening the same database?

Edit: to the question where it is stored: [link](https://github.com/Thinkwise/cordova-plugin-websql/blob/c1a211453776e1aa1f134b7e7243866eacaab732/src/windows/SQLiteConnectionManager.cs#L29)

I also updated the sqlite library today to a newer version, not sure if it helps though but might be worth checking out

**Comment by jantonsg** [comment]
First of all sorry for the delay, I have been so busy with other projects... 

I will try to check it with the newer version and also I will try to find where database is stored to give you more information if the problem persist. 

Thanks so much for your effort, and I promise to test it during this week and I will tell you something asap. ;)

**Comment by jantonsg** [comment]
I have been testing again and now seems that it works fine, maybe sqlite update makes its effect. 

We are going to use this plugin with more projects, so if we find something we will tell you and we analyze/talk how we can help you to solve it. 

Thanks for all ;)

**Comment by DickvdBrink** [comment]
Thanks for letting me know it is working now!
If you find something I will be happy to look into it as it might be an issue for us too! :)
