### ISSUE TITLE
Publish the plugin to NPM

### ISSUE THREAD

**Issue by JamesMessinger** [Thinkwise/cordova-plugin-websql#2]
Cordova plugins are [moving to npm](https://github.com/cordova/apache-blog-posts/blob/master/2015-04-15-plugins-release-and-move-to-npm.md), so this plugin should be published to npm as `cordova-plugin-websql-async`.   Once this is done, I can update the [asynchronous IndexedDB plugin](https://github.com/ABB-Austin/cordova-plugin-indexeddb-async) to point to the npm package.

**Comment by DickvdBrink** [comment]
Published :) Thanks for the package.json required for this! :) 
https://www.npmjs.com/package/cordova-plugin-websql-async

**Comment by JamesMessinger** [comment]
cool.  I updated the IndexedDB plugin to point to your repo instead of my fork.   I decided to point to your GIT URL rather than the npm package for now so it'll work with both Cordova CLI 4.0 and 5.0.  I'll point to your npm package once Cordova 5.0 is more widespread.
