### ISSUE TITLE
Windows 8.1 supported?

### ISSUE THREAD

**Issue by flikogenso** [Thinkwise/cordova-plugin-websql#7]
Is this plugin supported Windows 8.1?

i get below error when i use this command: cordova run windows --release

C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets
(2003,5): error MSB3779: The processor architecture of the project being built
"Any CPU" is not supported by the referenced SDK "Microsoft.VCLibs, Version=12.
0". Please consider changing the targeted processor architecture of your projec
t (in Visual Studio this can be done through the Configuration Manager) to one
of the architectures supported by the SDK: "x86, ARM". [C:\Users\Administrator\
Documents\cordova 5.1.1\project\TourismSurvey1\platforms\windows\CordovaApp.Pho
ne.jsproj]
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets
(2003,5): error MSB3779: The processor architecture of the project being built
"Any CPU" is not supported by the referenced SDK "SQLite.WP81, Version=3.8.8.1"
. Please consider changing the targeted processor architecture of your project
(in Visual Studio this can be done through the Configuration Manager) to one of
 the architectures supported by the SDK: "x86, ARM". [C:\Users\Administrator\Do
cuments\cordova 5.1.1\project\TourismSurvey1\platforms\windows\CordovaApp.Phone
.jsproj]
ERROR: Error code 1 for command: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild
 with args: C:\Users\Administrator\Documents\cordova 5.1.1\project\TourismSurvey
1\platforms\windows\CordovaApp.Phone.jsproj,/clp:NoSummary;NoItemAndPropertyList
;Verbosity=minimal,/nologo,/p:Configuration=release,/p:Platform=anycpu
ERROR running one or more of the platforms: Error: cmd: Command failed with exit
 code 2
You may not have the required environment or OS to run this project

**Comment by DibranMulder** [comment]
Hello @flikogenso,

this plugin does support Windows 8.1. However you should provide a target namely win or phone. Just like the build calls stated in the readme of this repo. Please try the following:

```
cordova run windows --release -- --win
```

Note that the additional dashes are because of a bug in Apache Cordova.
